### ISSUE TITLE
Got SyntaxError while importing from package

### ISSUE THREAD

**Issue by devanghingu** [chris-greening/instascrape#137]
I just installed latest version of this package in **virtualenv** through pip3. 
While importing anything from module i got following error., 
```
>>> from instascrape import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dev/env/scraping/lib/python3.6/site-packages/instascrape/__init__.py", line 1, in <module>
    from instascrape.scrapers import * 
  File "/home/dev/env/scraping/lib/python3.6/site-packages/instascrape/scrapers/__init__.py", line 1, in <module>
    from instascrape.scrapers.profile import *
  File "/home/dev/env/scraping/lib/python3.6/site-packages/instascrape/scrapers/profile.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

```

**Python** version is `3.6.9` and **GCC** version is  `8.4.0`
if you need anything from my end. Please let me know.

**Comment by devanghingu** [comment]
After reading documentation closing this issue due to lower python version.  :smile:
