### ISSUE TITLE
ValueError while Scrapping Posts

### ISSUE THREAD

**Issue by InzamamAnwar** [chris-greening/instascrape#156]
**Describe the bug**
Scrapping post using `Post` method gives error.
```
Traceback (most recent call last):
  File "/instagram-scrapping/main.py", line 23, in <module>
    post.scrape(headers=headers)
  File "lib/python3.7/site-packages/instascrape/scrapers/post.py", line 88, in scrape
    return_instance.upload_date = datetime.datetime.fromtimestamp(return_instance.timestamp)
ValueError: Invalid value NaN (not a number)
```

**To Reproduce**
```
from instascrape import Post

headers = {'user-agent': '', 'cookie': 'sessionid:{SESSION_ID}'}

post = Post("https://www.instagram.com/p/CaDMviujr4q/")
post.scrape(headers=headers)

```

**Expected behavior**
Dictionary with Keys mentioned in [Wiki-Scrapped Data points](https://github.com/chris-greening/instascrape/wiki/Scraped-data-points#post)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04 LTS]
 - Browser [chrome]
 - Version [insta-scrape: 2.1.2, chrome: 98.0.4758.80, Python: 3.7.11]

**Comment by 89z** [comment]
I have an alternate package that works:

~~~go
package main

import (
   "fmt"
   "github.com/89z/mech/instagram"
)

func main() {
   login, err := instagram.NewLogin(username, password)
   if err != nil {
      panic(err)
   }
   items, err := login.Items("CaDMviujr4q")
   if err != nil {
      panic(err)
   }
   for _, item := range items {
      form, err := item.Format()
      if err != nil {
         panic(err)
      }
      fmt.Println(form)
   }
}
~~~

**Comment by InzamamAnwar** [comment]
@89z Thank You for your prompt reply, But I was looking solution(s) in Python.

**Comment by Lxand3r** [comment]
> I have an alternate package that works:
> 
> ```go
> package main
> import "github.com/89z/mech/instagram"
> 
> func main() {
>    login, err := instagram.NewLogin(username, password)
>    if err != nil {
>       panic(err)
>    }
>    items, err := login.Items("CaDMviujr4q")
>    if err != nil {
>       panic(err)
>    }
>    for _, item := range items {
>       println(item.Caption.Text)
>    }
> }
> ```

where is this suppose to go ?

**Comment by iCodePoet** [comment]
I have the same problem.

**Comment by akouirouk** [comment]
I have the same problem as well

**Comment by UmeSiyah** [comment]
Me too, I have tired with the example script for joebien, get the same error.

**Comment by gentzeng** [comment]
Likewise

**Comment by haganenoneko** [comment]
Same issue here. Can someone share the output of `Post` objects, e.g. from calling the `get_posts()` method on a `Profile`, or creating a `Post` directly. For me, pretty much all fields are `None`: 

```python
url = 'https://www.instagram.com/google/'

google = Profile(url)
google.url = url 
google.scrape(headers=headers)

posts = google.get_posts(webdriver=driver, amount=2, 
    scrape=False, scrape_pause=5, 
    login_first=False, login_pause=50)

for post in posts:
    print(post.__dict__)
```

Output:
```
{'source': 'CbqJU0TjhJF', 'url': None, 'html': None, 'soup': None, 'json_dict': None, 'flat_json_dict': None, 'scrape_timestamp': None}
{'source': 'CbnUOtojevA', 'url': None, 'html': None, 'soup': None, 'json_dict': None, 'flat_json_dict': None, 'scrape_timestamp': None}
```

**Comment by Chocomagma** [comment]
I have the same problem as well

**Comment by Chocomagma** [comment]
I have the same problem as well

**Comment by Suizer** [comment]
same issue
