### ISSUE TITLE
Error scraping photos: ModuleNotFoundError: No module named 'helpers'

### ISSUE THREAD

**Issue by scr3wh34d** [chris-greening/instascrape#169]
Hello, using the example from your blog post I tried to scrape photos from a profile. It results in the following error:

`Traceback (most recent call last):
  File "/home/user/PycharmProjects/pythonProject2/main.py", line 1, in <module>
    from instascrape import Profile
  File "/home/user/PycharmProjects/pythonProject2/venv/lib/python3.10/site-packages/instascrape/__init__.py", line 4, in <module>
    from helpers import extract_email
ModuleNotFoundError: No module named 'helpers'`

**Comment by Titan-Ritam** [comment]
> Hello, using the example from your blog post I tried to scrape photos from a profile. It results in the following error:
> 
> `Traceback (most recent call last): File "/home/user/PycharmProjects/pythonProject2/main.py", line 1, in <module> from instascrape import Profile File "/home/user/PycharmProjects/pythonProject2/venv/lib/python3.10/site-packages/instascrape/__init__.py", line 4, in <module> from helpers import extract_email ModuleNotFoundError: No module named 'helpers'`

Same Problem

**Comment by payasparab** [comment]
Likely the issue is the same as this: make sure you install the right one: 
`pip install insta-scrape 
`
https://github.com/chris-greening/instascrape/issues/95#issuecomment-812327002
