### ISSUE TITLE
its gives an error when i try to download the reel 

### ISSUE THREAD

**Issue by pdxpro0098** [chris-greening/instascrape#170]
Traceback (most recent call last):
  File "c:\Users\Intel\Desktop\PROGRAMING PROJECT\python_files\INSTAdownloader.py", line 17, in <module>
    google_reel.scrape(headers=headers)
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python311\Lib\site-packages\instascrape\scrapers\post.py", line 73, in scrape
    return_instance = super().scrape(
                      ^^^^^^^^^^^^^^^
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python311\Lib\site-packages\instascrape\core\_static_scraper.py", line 144, in scrape
    return_data = self._get_json_from_source(self.source, headers=headers, session=session)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python311\Lib\site-packages\instascrape\core\_static_scraper.py", line 260, in _get_json_from_source
    json_dict_arr = json_from_soup(soup)
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python311\Lib\site-packages\instascrape\scrapers\scrape_tools.py", line 94, in json_from_soup 
    json_data = [json.loads(json_str) for json_str in json_data]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python311\Lib\site-packages\instascrape\scrapers\scrape_tools.py", line 94, in <listcomp>     
    json_data = [json.loads(json_str) for json_str in json_data]
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by king-of-Jupiter** [comment]
same error
